### ISSUE TITLE
Coursier installs amd64 version of scala-cli on a Apple arm64 machine

### ISSUE THREAD

**Issue by lolgab** [VirtusLab/scala-cli#2941]
**Is your feature request related to a problem? Please describe.**
If I install scala-cli through Coursier I get a version for a different architecture which runs under the rosetta emulator.
I know that Coursier is not the official way to install scala-cli but many people use it to install Scala tooling, and this can be a problem.

**Comment by bishabosha** [comment]
I think this is the code that determines the right platform: https://github.com/coursier/coursier/blob/8ca9b68447a1ba01aea5954b07b86e8ea05412f0/modules/install/src/main/scala/coursier/install/Platform.scala#L11

**Comment by kasiaMarek** [comment]
Which version of coursier are you using? I can reproduce that on some older versions but it seems to be working as expected now.

**Comment by lolgab** [comment]
<img width="1177" alt="example" src="https://github.com/VirtusLab/scala-cli/assets/5793054/dac08c9d-cc69-4bbc-8931-944b08618295">

It still tries to download the `x86_64` version on my Mac `arm64` machine

**Comment by kasiaMarek** [comment]
<img width="731" alt="Screenshot 2024-05-27 at 13 24 52" src="https://github.com/VirtusLab/scala-cli/assets/26606662/de01bdb9-6ddc-4422-a352-da7bb86c9388">

I'm doing the same thing, so I'm guessing the issue is more complex.

**Comment by bishabosha** [comment]
@lolgab it would be good to know which jvm is running when you do this resolution - perhaps it is an x86 one, or to know which cs launcher you installed - its architecture might be baked in

**Comment by Gedochao** [comment]
I suspect this has been fixed by https://github.com/coursier/apps/pull/246
@lolgab can you confirm?

**Comment by lolgab** [comment]
I still have the same issue:
<img width="1232" alt="scala-cli" src="https://github.com/user-attachments/assets/22e1cd6a-1a33-4db9-8653-3ad983325b41">

**EDIT**
Let me check with last commit of coursier

**Comment by Gedochao** [comment]
@lolgab The change has been released in [coursier/apps v1.0.56](https://github.com/coursier/apps/releases/tag/v1.0.56) just now, not sure if it's fully online yet (29 minutes ago as of this comment).

**Comment by tgodzik** [comment]
I wonder if adding `--architecture aarch64` or `--architecture aarch64-linux` would help :thinking:

**Comment by ploffredi** [comment]
> @lolgab The change has been released in [coursier/apps v1.0.56](https://github.com/coursier/apps/releases/tag/v1.0.56) just now, not sure if it's fully online yet (29 minutes ago as of this comment).

@Gedochao @lolgab I don’t believe this change will resolve the issue, as it was made specifically for aarch64-linux systems and does not impact aarch64-apple-darwin architectures, such as those on Apple Silicon.
